### PR TITLE
Optimize a few constructions

### PR DESCRIPTION
**Pull request by devsedo**
Use optional chaining. Optimize while-loop while trimming an array by N last elements. Remove initialization of Optionals with nil (they're nil by default).

### CODE REVIEW

**Comment by hfossli** [comment]
Well hello! Thanks for these 3 pull requests. It sure was a nice thing to see this morning! Thanks a lot! I'm not coding in swift *that* much so I don't know all best practices. Originally I made this a shell script, but it was veeeery slow. One file took over a minute to parse while with swift it took 0.06 seconds 😂 Anyways, thanks again! ❤️

**Comment by hfossli** [comment]
In what ways did this library help you? Are you satisfied with what it is doing with the output? Or do you want something changed?

**Comment by devsedo** [comment]
@hfossli I was just surfing github projects to see if I can make any contribution.

**Comment by hfossli** [comment]
That is just amazing! 🙌

**Comment by hfossli** [comment]
Are you on twitter?

**Comment by devsedo** [comment]
@hfossli sure [@edsergeev](https://twitter.com/edsergeev)

**Pull request merged**
